# Generated by Django 5.0.2 on 2024-04-18 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busregno', models.CharField(max_length=50)),
                ('busmodel', models.CharField(max_length=50)),
                ('chasisnumber', models.CharField(max_length=50)),
                ('manufacturename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.CharField(max_length=250)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routename', models.CharField(max_length=50)),
                ('fromplace', models.CharField(max_length=50)),
                ('toplace', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Allocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.bus')),
                ('DRIVER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.bus')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='LOGIN',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MyApp.login'),
        ),
        migrations.CreateModel(
            name='Busstop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placename', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('ROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.route')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='ROUTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.route'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('trip', models.CharField(max_length=50)),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.bus')),
                ('BUSSTOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.busstop')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneno', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('idproof', models.CharField(max_length=500)),
                ('LOOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.login')),
            ],
        ),
    ]
